import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'el', 'fr', 'zh_Hans', 'es', 'it', 'he'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? elText = '',
    String? frText = '',
    String? zh_HansText = '',
    String? esText = '',
    String? itText = '',
    String? heText = '',
  }) =>
      [
        enText,
        elText,
        frText,
        zh_HansText,
        esText,
        itText,
        heText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // recipeDetails
  {
    'xhbucuyd': {
      'en': 'Instructions:',
      'el': 'Οδηγίες:',
      'es': 'Instrucciones:',
      'fr': 'Instructions:',
      'he': 'הוראות:',
      'it': 'Istruzioni:',
      'zh_Hans': '指示：',
    },
    '79c9bdav': {
      'en': 'Ingredients:',
      'el': 'Συστατικά:',
      'es': 'Ingredientes:',
      'fr': 'Ingrédients:',
      'he': 'רכיבים:',
      'it': 'Ingredienti:',
      'zh_Hans': '原料：',
    },
    'a4ikx5qk': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // CreateRecipe
  {
    'wyghwea4': {
      'en': 'Find New Recipies',
      'el': 'Βρείτε νέες συνταγές',
      'es': 'Encuentra nuevas recetas',
      'fr': 'Trouver de nouvelles recettes',
      'he': 'מצא מתכונים חדשים',
      'it': 'Trova nuove ricette',
      'zh_Hans': '寻找新食谱',
    },
    '9hky9wlz': {
      'en':
          'Provide a list of ingredients and we\'ll tell you what you can wake with them!',
      'el':
          'Δώστε μια λίστα με συστατικά και θα σας πούμε τι μπορείτε να ξυπνήσετε με αυτά!',
      'es':
          '¡Proporciona una lista de ingredientes y te diremos qué puedes despertar con ellos!',
      'fr':
          'Fournissez une liste d\'ingrédients et nous vous dirons ce que vous pouvez réveiller avec eux !',
      'he': 'ספק רשימה של מרכיבים ואנו אגיד לך מה אתה יכול להעיר איתם!',
      'it':
          'Fornisci un elenco di ingredienti e ti diremo cosa puoi svegliare con loro!',
      'zh_Hans': '提供成分清单，我们会告诉您可以用它们唤醒什么！',
    },
    '45wma1h4': {
      'en': 'Enter the ingredients you have on hand',
      'el': 'Εισαγάγετε τα υλικά που έχετε στη διάθεσή σας',
      'es': 'Introduce los ingredientes que tienes a mano',
      'fr': 'Entrez les ingrédients que vous avez sous la main',
      'he': 'הזן את החומרים שיש לך בהישג יד',
      'it': 'Inserisci gli ingredienti che hai a portata di mano',
      'zh_Hans': '输入您现有的成分',
    },
    'o77r9xik': {
      'en': 'Ingredients...',
      'el': 'Συστατικά...',
      'es': 'Ingredientes...',
      'fr': 'Ingrédients...',
      'he': 'רכיבים...',
      'it': 'Ingredienti...',
      'zh_Hans': '原料...',
    },
    '83webv9g': {
      'en': 'Enter the condiments, seasoning, and sauces you have on hand.',
      'el':
          'Εισαγάγετε τα καρυκεύματα, τα καρυκεύματα και τις σάλτσες που έχετε στη διάθεσή σας.',
      'es': 'Ingresa los condimentos, aderezos y salsas que tengas a mano.',
      'fr':
          'Entrez les condiments, assaisonnements et sauces que vous avez sous la main.',
      'he': 'הכניסו את התבלינים, התיבול והרטבים שיש לכם בהישג יד.',
      'it':
          'Inserisci i condimenti, i condimenti e le salse che hai a portata di mano.',
      'zh_Hans': '输入您手头的调味品、调料和酱汁。',
    },
    '61yhukpg': {
      'en': 'Condiments, seasoning and sauces...',
      'el': 'Καρυκεύματα, καρυκεύματα και σάλτσες...',
      'es': 'Condimentos, aliños y salsas...',
      'fr': 'Condiments, assaisonnements et sauces...',
      'he': 'תבלינים, תיבול ורטבים...',
      'it': 'Condimenti, condimenti e salse...',
      'zh_Hans': '调味品、调料和酱料...',
    },
    '37x86g0c': {
      'en': 'Available leftovers (Optional)',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)',
      'es': 'Sobras disponibles (Opcional)',
      'fr': 'Restes disponibles (facultatif)',
      'he': 'שאריות זמינות (אופציונלי)',
      'it': 'Avanzi disponibili (facoltativo)',
      'zh_Hans': '可用的剩菜（可选）',
    },
    '1dq6vb1s': {
      'en': 'Available leftovers (Optional)...',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)...',
      'es': 'Sobras disponibles (Opcional)...',
      'fr': 'Restes disponibles (Facultatif)...',
      'he': 'שאריות זמינות (אופציונלי)...',
      'it': 'Avanzi disponibili (facoltativo)...',
      'zh_Hans': '可用的剩菜（可选）...',
    },
    'zjmmdqlp': {
      'en': 'Type of Meal',
      'el': 'Είδος Γεύματος',
      'es': 'Tipo de comida',
      'fr': 'Type de repas',
      'he': 'סוג הארוחה',
      'it': 'Tipo di pasto',
      'zh_Hans': '膳食类型',
    },
    'hdapt8yw': {
      'en': 'Please select what time of day you want the meal',
      'el': 'Επιλέξτε ποια ώρα της ημέρας θέλετε το γεύμα',
      'es': 'Por favor seleccione a qué hora del día desea la comida.',
      'fr':
          'Veuillez sélectionner l\'heure de la journée à laquelle vous souhaitez le repas',
      'he': 'אנא בחר באיזו שעה ביום אתה רוצה את הארוחה',
      'it': 'Seleziona l\'ora del giorno in cui desideri il pasto',
      'zh_Hans': '请选择您想要用餐的时间',
    },
    'voelnu9b': {
      'en': 'Breakfast',
      'el': 'ΠΡΩΙΝΟ ΓΕΥΜΑ',
      'es': 'Desayuno',
      'fr': 'Petit-déjeuner',
      'he': 'ארוחת בוקר',
      'it': 'Colazione',
      'zh_Hans': '早餐',
    },
    '87ho4ceu': {
      'en': 'Brunch',
      'el': 'Μεσημεριανό',
      'es': 'Desalmuerzo',
      'fr': 'Brunch',
      'he': 'בראנץ\'',
      'it': 'Brunch',
      'zh_Hans': '早午餐',
    },
    'ulib0d6s': {
      'en': 'Lunch',
      'el': 'Μεσημεριανό',
      'es': 'Almuerzo',
      'fr': 'Déjeuner',
      'he': 'ארוחת צהריים',
      'it': 'Pranzo',
      'zh_Hans': '午餐',
    },
    'ndm65i1k': {
      'en': 'Dinner',
      'el': 'Βραδινό',
      'es': 'Cena',
      'fr': 'Dîner',
      'he': 'אֲרוּחַת עֶרֶב',
      'it': 'Cena',
      'zh_Hans': '晚餐',
    },
    'a6jso50c': {
      'en': 'Available Time',
      'el': 'Διαθέσιμος χρόνος',
      'es': 'Tiempo disponible',
      'fr': 'Temps disponible',
      'he': 'זמן פנוי',
      'it': 'Tempo disponibile',
      'zh_Hans': '有空时间',
    },
    'ihs0yb7a': {
      'en': 'Please select how much  time you have to make this meal',
      'el': 'Επιλέξτε πόσο χρόνο έχετε για να φτιάξετε αυτό το γεύμα',
      'es':
          'Por favor selecciona cuánto tiempo tienes para preparar esta comida.',
      'fr':
          'Veuillez sélectionner le temps dont vous disposez pour préparer ce repas',
      'he': 'אנא בחר כמה זמן יש לך להכין את הארוחה הזו',
      'it': 'Seleziona quanto tempo hai per preparare questo pasto',
      'zh_Hans': '请选择您需要多长时间来做这顿饭',
    },
    'juzf3y71': {
      'en': '5 min',
      'el': '5 λεπτά',
      'es': '5 minutos',
      'fr': '5 minutes',
      'he': '5 דקות',
      'it': '5 minuti',
      'zh_Hans': '5分钟',
    },
    'hegbzyx5': {
      'en': '15 min',
      'el': '15 λεπτά',
      'es': '15 minutos',
      'fr': '15 min',
      'he': '15 דקות',
      'it': '15 minuti',
      'zh_Hans': '15分钟',
    },
    'h4xsybxo': {
      'en': '30 min',
      'el': '30 λεπτά',
      'es': '30 minutos',
      'fr': '30 minutes',
      'he': '30 דק',
      'it': '30 minuti',
      'zh_Hans': '30分钟',
    },
    'tpy3ke25': {
      'en': '1 hour',
      'el': '1 ώρα',
      'es': '1 hora',
      'fr': '1 heure',
      'he': '1 שעה',
      'it': '1 ora',
      'zh_Hans': '1小时',
    },
    'gqz7hg8x': {
      'en': '2 hours',
      'el': '2 ώρες',
      'es': '2 horas',
      'fr': '2 heures',
      'he': '2 שעות',
      'it': '2 ore',
      'zh_Hans': '2小时',
    },
    'wm5hsb1s': {
      'en': 'infinite',
      'el': 'άπειρος',
      'es': 'infinito',
      'fr': 'infini',
      'he': 'אֵינְסוֹף',
      'it': 'infinito',
      'zh_Hans': '无穷',
    },
    'q8lqcaym': {
      'en': 'Generate Recipies',
      'el': 'Δημιουργία συνταγών',
      'es': 'Generar recetas',
      'fr': 'Générer des recettes',
      'he': 'צור מתכונים',
      'it': 'Genera ricette',
      'zh_Hans': '生成食谱',
    },
    'wjgshfr7': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '1tb1rivq': {
      'en': 'Menu',
      'el': 'Μενού',
      'es': 'Menú',
      'fr': 'Menu',
      'he': 'תַפרִיט',
      'it': 'Menù',
      'zh_Hans': '菜单',
    },
    'a0t2k0co': {
      'en': 'Light Mode',
      'el': 'Λειτουργία φωτός',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'he': 'מצב אור',
      'it': 'Modalità luce',
      'zh_Hans': '灯光模式',
    },
    '0oc6lxcz': {
      'en': 'Dark Mode',
      'el': 'Σκοτεινή λειτουργία',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'he': 'מצב כהה',
      'it': 'Modalità scura',
      'zh_Hans': '深色模式',
    },
    'nz47o0cg': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // Login
  {
    'pi2fp0xe': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'kqlvn0vt': {
      'en': 'Create Account',
      'el': 'Δημιουργήστε λογαριασμό',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'he': 'צור חשבון',
      'it': 'Creare un account',
      'zh_Hans': '创建账户',
    },
    'kl41bult': {
      'en': 'Create Account',
      'el': 'Δημιουργήστε λογαριασμό',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'he': 'צור חשבון',
      'it': 'Creare un account',
      'zh_Hans': '创建账户',
    },
    'z3ekx0l8': {
      'en': 'Let\'s get started by filling out the form below.',
      'el': 'Ας ξεκινήσουμε συμπληρώνοντας την παρακάτω φόρμα.',
      'es': 'Comencemos completando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'he': 'בואו נתחיל על ידי מילוי הטופס למטה.',
      'it': 'Iniziamo compilando il modulo sottostante.',
      'zh_Hans': '让我们开始填写下面的表格。',
    },
    'uww47kva': {
      'en': 'Email',
      'el': 'ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'he': 'אימייל',
      'it': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    '9p9aegbs': {
      'en': 'Password',
      'el': 'Κωδικός πρόσβασης',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'he': 'סיסמה',
      'it': 'Parola d\'ordine',
      'zh_Hans': '密码',
    },
    'xt2q79rm': {
      'en': 'Confirm Password',
      'el': 'Επιβεβαίωση Κωδικού',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'he': 'אשר סיסמה',
      'it': 'Conferma password',
      'zh_Hans': '确认密码',
    },
    '0zfk0v8x': {
      'en': 'Get Started',
      'el': 'Ξεκίνα',
      'es': 'Empezar',
      'fr': 'Commencer',
      'he': 'להתחיל',
      'it': 'Iniziare',
      'zh_Hans': '开始使用',
    },
    'f9x272es': {
      'en': 'Or sign up with',
      'el': 'Ή εγγραφείτε με',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'he': 'או להירשם עם',
      'it': 'Oppure registrati con',
      'zh_Hans': '或者注册',
    },
    'x7lvsg7m': {
      'en': 'Continue with Google',
      'el': 'Συνεχίστε με την Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'he': 'המשך עם גוגל',
      'it': 'Continua con Google',
      'zh_Hans': '继续使用谷歌',
    },
    'ywy6r8ja': {
      'en': 'Continue with Apple',
      'el': 'Συνεχίστε με την Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'he': 'המשך עם אפל',
      'it': 'Continua con Apple',
      'zh_Hans': '继续使用苹果',
    },
    '8ttpf53r': {
      'en': 'Log In',
      'el': 'Σύνδεση',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'he': 'התחברות',
      'it': 'Login',
      'zh_Hans': '登录',
    },
    'p3jq1rth': {
      'en': 'Welcome Back',
      'el': 'Καλως ορισες πισω',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'he': 'ברוך שובך',
      'it': 'Bentornato',
      'zh_Hans': '欢迎回来',
    },
    '1bzpl5f5': {
      'en': 'Fill out the information below in order to access your account.',
      'el':
          'Συμπληρώστε τις παρακάτω πληροφορίες για να αποκτήσετε πρόσβαση στον λογαριασμό σας.',
      'es': 'Complete la información a continuación para acceder a su cuenta.',
      'fr':
          'Remplissez les informations ci-dessous afin d\'accéder à votre compte.',
      'he': 'מלא את המידע למטה כדי לגשת לחשבון שלך.',
      'it': 'Compila le informazioni seguenti per accedere al tuo account.',
      'zh_Hans': '填写以下信息以访问您的帐户。',
    },
    '65ndiovm': {
      'en': 'Email',
      'el': 'ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'he': 'אימייל',
      'it': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'x4uu6huf': {
      'en': 'Password',
      'el': 'Κωδικός πρόσβασης',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'he': 'סיסמה',
      'it': 'Parola d\'ordine',
      'zh_Hans': '密码',
    },
    '6qvilc6k': {
      'en': 'Sign In',
      'el': 'Συνδεθείτε',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'he': 'להתחבר',
      'it': 'Registrazione',
      'zh_Hans': '登入',
    },
    'z5wonppu': {
      'en': 'Or sign in with',
      'el': 'Ή συνδεθείτε με',
      'es': 'O inicia sesión con',
      'fr': 'Ou connectez-vous avec',
      'he': 'או היכנס עם',
      'it': 'Oppure accedi con',
      'zh_Hans': '或者登录',
    },
    'o8kjh2lz': {
      'en': 'Continue with Google',
      'el': 'Συνεχίστε με την Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'he': 'המשך עם גוגל',
      'it': 'Continua con Google',
      'zh_Hans': '继续使用谷歌',
    },
    'bzh273nl': {
      'en': 'Continue with Apple',
      'el': 'Συνεχίστε με την Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'he': 'המשך עם אפל',
      'it': 'Continua con Apple',
      'zh_Hans': '继续使用苹果',
    },
    'kzsaoaen': {
      'en': 'Forgot Password?',
      'el': 'Ξεχάσατε τον κωδικό;',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'he': 'שכחת את הסיסמא?',
      'it': 'Ha dimenticato la password?',
      'zh_Hans': '忘记密码？',
    },
    'i6sso3fq': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // Inventory
  {
    'wqqyw4gl': {
      'en': 'Inventory',
      'el': 'Καταγραφή εμπορευμάτων',
      'es': 'Inventario',
      'fr': 'Inventaire',
      'he': 'מְלַאי',
      'it': 'Inventario',
      'zh_Hans': '存货',
    },
    '8ymlzker': {
      'en': 'List of current groceries',
      'el': 'Λίστα με τρέχοντα είδη παντοπωλείου',
      'es': 'Lista de comestibles actuales',
      'fr': 'Liste des courses actuelles',
      'he': 'רשימת מצרכים עדכניים',
      'it': 'Elenco della spesa corrente',
      'zh_Hans': '当前杂货清单',
    },
    '5c700uvt': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'a42e5p7u': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '1ngqwoj3': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'jtkd2si4': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'xn8o5053': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'rrsniy4r': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    '8cmltkz8': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'r3u97cna': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'dqk4daaq': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'oe9o9v4s': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'ffbdhbr4': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'mlk84ymp': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'wxto50y0': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    '47xsfdzy': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'kwedplak': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'c8z3iimk': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'pyrlkewb': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '4n17pyu3': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'ofh0rf85': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // CreateRecipeCopy
  {
    '1776dyhc': {
      'en': 'Find New Recipies',
      'el': 'Βρείτε νέες συνταγές',
      'es': 'Encuentra nuevas recetas',
      'fr': 'Trouver de nouvelles recettes',
      'he': 'מצא מתכונים חדשים',
      'it': 'Trova nuove ricette',
      'zh_Hans': '寻找新食谱',
    },
    '0waxypi3': {
      'en':
          'Provide a list of ingredients and we\'ll tell you what you can wake with them!',
      'el':
          'Δώστε μια λίστα με συστατικά και θα σας πούμε τι μπορείτε να ξυπνήσετε με αυτά!',
      'es':
          '¡Proporciona una lista de ingredientes y te diremos qué puedes despertar con ellos!',
      'fr':
          'Fournissez une liste d\'ingrédients et nous vous dirons ce que vous pouvez réveiller avec eux !',
      'he': 'ספק רשימה של מרכיבים ואנו אגיד לך מה אתה יכול להעיר איתם!',
      'it':
          'Fornisci un elenco di ingredienti e ti diremo cosa puoi svegliare con loro!',
      'zh_Hans': '提供成分清单，我们会告诉您可以用它们唤醒什么！',
    },
    '7wpydnn7': {
      'en': 'Enter the ingredients you have on hand',
      'el': 'Εισαγάγετε τα υλικά που έχετε στη διάθεσή σας',
      'es': 'Introduce los ingredientes que tienes a mano',
      'fr': 'Entrez les ingrédients que vous avez sous la main',
      'he': 'הזן את החומרים שיש לך בהישג יד',
      'it': 'Inserisci gli ingredienti che hai a portata di mano',
      'zh_Hans': '输入您现有的成分',
    },
    'ww0fpm9f': {
      'en': 'Ingredients...',
      'el': 'Συστατικά...',
      'es': 'Ingredientes...',
      'fr': 'Ingrédients...',
      'he': 'רכיבים...',
      'it': 'Ingredienti...',
      'zh_Hans': '原料...',
    },
    'kwjelof4': {
      'en': 'Enter the condiments, seasoning, and sauces you have on hand.',
      'el':
          'Εισαγάγετε τα καρυκεύματα, τα καρυκεύματα και τις σάλτσες που έχετε στη διάθεσή σας.',
      'es': 'Ingresa los condimentos, aderezos y salsas que tengas a mano.',
      'fr':
          'Entrez les condiments, assaisonnements et sauces que vous avez sous la main.',
      'he': 'הכניסו את התבלינים, התיבול והרטבים שיש לכם בהישג יד.',
      'it':
          'Inserisci i condimenti, i condimenti e le salse che hai a portata di mano.',
      'zh_Hans': '输入您手头的调味品、调料和酱汁。',
    },
    '33nurh1d': {
      'en': 'Condiments, seasoning and sauces...',
      'el': 'Καρυκεύματα, καρυκεύματα και σάλτσες...',
      'es': 'Condimentos, aliños y salsas...',
      'fr': 'Condiments, assaisonnements et sauces...',
      'he': 'תבלינים, תיבול ורטבים...',
      'it': 'Condimenti, condimenti e salse...',
      'zh_Hans': '调味品、调料和酱料...',
    },
    '78mf053u': {
      'en': 'Available leftovers (Optional)',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)',
      'es': 'Sobras disponibles (Opcional)',
      'fr': 'Restes disponibles (facultatif)',
      'he': 'שאריות זמינות (אופציונלי)',
      'it': 'Avanzi disponibili (facoltativo)',
      'zh_Hans': '可用的剩菜（可选）',
    },
    'soieokzo': {
      'en': 'Available leftovers (Optional)...',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)...',
      'es': 'Sobras disponibles (Opcional)...',
      'fr': 'Restes disponibles (Facultatif)...',
      'he': 'שאריות זמינות (אופציונלי)...',
      'it': 'Avanzi disponibili (facoltativo)...',
      'zh_Hans': '可用的剩菜（可选）...',
    },
    '9h28p7nf': {
      'en': 'Type of Meal',
      'el': 'Είδος Γεύματος',
      'es': 'Tipo de comida',
      'fr': 'Type de repas',
      'he': 'סוג הארוחה',
      'it': 'Tipo di pasto',
      'zh_Hans': '膳食类型',
    },
    'rnalmn45': {
      'en': 'Please select what time of day you want the meal',
      'el': 'Επιλέξτε ποια ώρα της ημέρας θέλετε το γεύμα',
      'es': 'Por favor seleccione a qué hora del día desea la comida.',
      'fr':
          'Veuillez sélectionner l\'heure de la journée à laquelle vous souhaitez le repas',
      'he': 'אנא בחר באיזו שעה ביום אתה רוצה את הארוחה',
      'it': 'Seleziona l\'ora del giorno in cui desideri il pasto',
      'zh_Hans': '请选择您想要用餐的时间',
    },
    '23h5hooq': {
      'en': 'Breakfast',
      'el': 'ΠΡΩΙΝΟ ΓΕΥΜΑ',
      'es': 'Desayuno',
      'fr': 'Petit-déjeuner',
      'he': 'ארוחת בוקר',
      'it': 'Colazione',
      'zh_Hans': '早餐',
    },
    '7md0ygf7': {
      'en': 'Brunch',
      'el': 'Μεσημεριανό',
      'es': 'Desalmuerzo',
      'fr': 'Brunch',
      'he': 'בראנץ\'',
      'it': 'Brunch',
      'zh_Hans': '早午餐',
    },
    '01qy93sy': {
      'en': 'Lunch',
      'el': 'Μεσημεριανό',
      'es': 'Almuerzo',
      'fr': 'Déjeuner',
      'he': 'ארוחת צהריים',
      'it': 'Pranzo',
      'zh_Hans': '午餐',
    },
    '65bpegn2': {
      'en': 'Dinner',
      'el': 'Βραδινό',
      'es': 'Cena',
      'fr': 'Dîner',
      'he': 'אֲרוּחַת עֶרֶב',
      'it': 'Cena',
      'zh_Hans': '晚餐',
    },
    '3i4c9jmt': {
      'en': 'Available Time',
      'el': 'Διαθέσιμος χρόνος',
      'es': 'Tiempo disponible',
      'fr': 'Temps disponible',
      'he': 'זמן פנוי',
      'it': 'Tempo disponibile',
      'zh_Hans': '有空时间',
    },
    '8zr4m0kr': {
      'en': 'Please select how much  time you have to make this meal',
      'el': 'Επιλέξτε πόσο χρόνο έχετε για να φτιάξετε αυτό το γεύμα',
      'es':
          'Por favor selecciona cuánto tiempo tienes para preparar esta comida.',
      'fr':
          'Veuillez sélectionner le temps dont vous disposez pour préparer ce repas',
      'he': 'אנא בחר כמה זמן יש לך להכין את הארוחה הזו',
      'it': 'Seleziona quanto tempo hai per preparare questo pasto',
      'zh_Hans': '请选择您需要多长时间来做这顿饭',
    },
    '8gpv2336': {
      'en': '5 min',
      'el': '5 λεπτά',
      'es': '5 minutos',
      'fr': '5 minutes',
      'he': '5 דקות',
      'it': '5 minuti',
      'zh_Hans': '5分钟',
    },
    'mbittml9': {
      'en': '15 min',
      'el': '15 λεπτά',
      'es': '15 minutos',
      'fr': '15 min',
      'he': '15 דקות',
      'it': '15 minuti',
      'zh_Hans': '15分钟',
    },
    '5970mgpd': {
      'en': '30 min',
      'el': '30 λεπτά',
      'es': '30 minutos',
      'fr': '30 minutes',
      'he': '30 דק',
      'it': '30 minuti',
      'zh_Hans': '30分钟',
    },
    'kfvr4ni9': {
      'en': '1 hour',
      'el': '1 ώρα',
      'es': '1 hora',
      'fr': '1 heure',
      'he': '1 שעה',
      'it': '1 ora',
      'zh_Hans': '1小时',
    },
    'dsiyixy7': {
      'en': '2 hours',
      'el': '2 ώρες',
      'es': '2 horas',
      'fr': '2 heures',
      'he': '2 שעות',
      'it': '2 ore',
      'zh_Hans': '2小时',
    },
    '9nn30dgr': {
      'en': 'infinite',
      'el': 'άπειρος',
      'es': 'infinito',
      'fr': 'infini',
      'he': 'אֵינְסוֹף',
      'it': 'infinito',
      'zh_Hans': '无穷',
    },
    '9vpvp0sr': {
      'en': 'Generate Recipies',
      'el': 'Δημιουργία συνταγών',
      'es': 'Generar recetas',
      'fr': 'Générer des recettes',
      'he': 'צור מתכונים',
      'it': 'Genera ricette',
      'zh_Hans': '生成食谱',
    },
    'x4nljjs6': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'tmqjionz': {
      'en': 'Menu',
      'el': 'Μενού',
      'es': 'Menú',
      'fr': 'Menu',
      'he': 'תַפרִיט',
      'it': 'Menù',
      'zh_Hans': '菜单',
    },
    'bqr8htar': {
      'en': 'Light Mode',
      'el': 'Λειτουργία φωτός',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'he': 'מצב אור',
      'it': 'Modalità luce',
      'zh_Hans': '灯光模式',
    },
    'ejdn2az6': {
      'en': 'Dark Mode',
      'el': 'Σκοτεινή λειτουργία',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'he': 'מצב כהה',
      'it': 'Modalità scura',
      'zh_Hans': '深色模式',
    },
    'skszh1cn': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // SearchImage
  {
    '0viu9dkb': {
      'en': 'Upload an Image',
      'el': 'Ανεβάστε μια εικόνα',
      'es': 'Subir una imagen',
      'fr': 'Télécharger une image',
      'he': 'העלה תמונה',
      'it': 'Carica un\'immagine',
      'zh_Hans': '上传图片',
    },
    '5baaij54': {
      'en': 'OR',
      'el': 'Ή',
      'es': 'O',
      'fr': 'OU',
      'he': 'אוֹ',
      'it': 'O',
      'zh_Hans': '或者',
    },
    'cqwxyx1x': {
      'en': 'Input URL',
      'el': 'Εισαγωγή URL',
      'es': 'URL de entrada',
      'fr': 'URL d\'entrée',
      'he': 'הזן כתובת אתר',
      'it': 'Inserisci l\'URL',
      'zh_Hans': '输入网址',
    },
    'ojg7s49j': {
      'en': 'Context',
      'el': 'Συμφραζόμενα',
      'es': 'Contexto',
      'fr': 'Contexte',
      'he': 'הֶקשֵׁר',
      'it': 'Contesto',
      'zh_Hans': '语境',
    },
    'z0jvh04n': {
      'en': 'Does it look good or its spoilt?',
      'el': 'Εξακολουθεί να φαίνεται καλό ή είναι χαλασμένο;',
      'es': '¿Aún se ve bien o está estropeado?',
      'fr': 'Est-ce qu\'il a toujours l\'air bien ou est-il gâté ?',
      'he': 'האם זה עדיין נראה טוב או שהוא מפונק?',
      'it': 'Ha ancora un bell\'aspetto o è rovinato?',
      'zh_Hans': '它看起来还不错还是已经被破坏了？',
    },
    '2exuj78i': {
      'en': 'Copilot\'s Response',
      'el': 'Η απάντηση του Copilot',
      'es': 'La respuesta del copiloto',
      'fr': 'Réponse du copilote',
      'he': 'תגובת פיילוט',
      'it': 'La risposta del copilota',
      'zh_Hans': '副驾驶的回应',
    },
    '36mb8lzo': {
      'en': 'Ask about Product',
      'el': 'Ρωτήστε για το προϊόν',
      'es': 'Preguntar sobre el producto',
      'fr': 'Renseignez-vous sur le produit',
      'he': 'שאל על המוצר',
      'it': 'Chiedi informazioni sul prodotto',
      'zh_Hans': '询问产品',
    },
    'aix90usm': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '63q4jft6': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // TalkToAI
  {
    'w49y0g2k': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '27xzotz5': {
      'en': 'Tap to Speak',
      'el': 'Πατήστε για να μιλήσετε',
      'es': 'Toca para hablar',
      'fr': 'Appuyez pour parler',
      'he': 'הקש כדי לדבר',
      'it': 'Tocca per parlare',
      'zh_Hans': '点击说话',
    },
    'xcsixe93': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // settings
  {
    'tuf7u61b': {
      'en': 'Settings Page',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'yi0oem2q': {
      'en': 'Getting Started',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'c7sitweq': {
      'en': 'About me',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '6tw67qoc': {
      'en': 'Help',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'cawk0eg9': {
      'en': 'Privacy Policy',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'nzfoc30r': {
      'en': 'Terms & Conditions',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0ish1v7n': {
      'en': 'Select Language',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'd299ize5': {
      'en':
          'The selected language determines the language the Copilot would respond with; both voice and script.',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0vvlstkk': {
      'en': 'Follow us on',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'ixnl31jo': {
      'en': 'App Versions',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'zqfpamt4': {
      'en': 'v0.0.1',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'fj6xlu8w': {
      'en': 'Log Out',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '9czda96d': {
      'en': 'Home',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
  },
  // HomePage
  {
    '75ky3amz': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'j64d6xwh': {
      'en': 'Recipies',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'kzr0fohl': {
      'en': 'Inventory',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '8xqfy9h6': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'n1qv1pvc': {
      'en': 'Talk to Copilot',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'gfde0i2h': {
      'en': 'Settings',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'r80eq3k6': {
      'en': 'About me',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'm4s4m45h': {
      'en': 'Home',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
  },
  // recipePage
  {
    'fbxqgqk4': {
      'en': 'Instructions:',
      'el': 'Οδηγίες:',
      'es': 'Instrucciones:',
      'fr': 'Instructions:',
      'he': 'הוראות:',
      'it': 'Istruzioni:',
      'zh_Hans': '指示：',
    },
    'qn5hkmn1': {
      'en': 'Ingredients:',
      'el': 'Συστατικά:',
      'es': 'Ingredientes:',
      'fr': 'Ingrédients:',
      'he': 'רכיבים:',
      'it': 'Ingredienti:',
      'zh_Hans': '原料：',
    },
    'bdrx4cu2': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // option
  {
    'xdgeubbj': {
      'en': 'Add Product',
      'el': 'Προσθήκη προϊόντος',
      'es': 'Agregar producto',
      'fr': 'Ajouter un produit',
      'he': 'הוסף מוצר',
      'it': 'Aggiungi prodotto',
      'zh_Hans': '添加产品',
    },
    's06sy6ue': {
      'en': 'Item Name',
      'el': 'Ονομα προϊόντος',
      'es': 'Nombre del árticulo',
      'fr': 'Nom de l\'article',
      'he': 'שם הפריט',
      'it': 'Nome dell\'elemento',
      'zh_Hans': '项目名',
    },
    '4o8l57ry': {
      'en': 'Quantity',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'n7qtjf2l': {
      'en': 'Price',
      'el': 'Τιμή',
      'es': 'Precio',
      'fr': 'Prix',
      'he': 'מחיר',
      'it': 'Prezzo',
      'zh_Hans': '价格',
    },
    'vqxny1fd': {
      'en': 'Category',
      'el': 'Τιμή',
      'es': 'Precio',
      'fr': 'Prix',
      'he': 'מחיר',
      'it': 'Prezzo',
      'zh_Hans': '价格',
    },
    '8yu7i0ld': {
      'en': 'Save',
      'el': 'Αποθηκεύσετε',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'he': 'להציל',
      'it': 'Salva',
      'zh_Hans': '节省',
    },
  },
  // tray
  {
    '835sccoa': {
      'en': 'Ask Copilot',
      'el': 'Ρωτήστε τον Copilot',
      'es': 'Preguntar al copiloto',
      'fr': 'Demandez au copilote',
      'he': 'תשאל קוטילוט',
      'it': 'Chiedi al copilota',
      'zh_Hans': '询问副驾驶',
    },
    'n13pgude': {
      'en': 'Create Recipe',
      'el': 'Δημιουργία συνταγής',
      'es': 'Crear receta',
      'fr': 'Créer une recette',
      'he': 'צור מתכון',
      'it': 'Crea ricetta',
      'zh_Hans': '创建食谱',
    },
    'yugna71g': {
      'en': 'Add Product',
      'el': 'Προσθήκη προϊόντος',
      'es': 'Agregar producto',
      'fr': 'Ajouter un produit',
      'he': 'הוסף מוצר',
      'it': 'Aggiungi prodotto',
      'zh_Hans': '添加产品',
    },
  },
  // Miscellaneous
  {
    'og69irt4': {
      'en': 'Button',
      'el': 'Κουμπί',
      'es': 'Botón',
      'fr': 'Bouton',
      'he': 'לַחְצָן',
      'it': 'Pulsante',
      'zh_Hans': '按钮',
    },
    'mnhc0oi3': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'fnlxb6np': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '35w160b6': {
      'en': 'Allow access to library to set an image of product',
      'el':
          'Επιτρέψτε την πρόσβαση στη βιβλιοθήκη για να ορίσετε μια εικόνα του προϊόντος',
      'es':
          'Permitir el acceso a la biblioteca para configurar una imagen del producto',
      'fr':
          'Autoriser l\'accès à la bibliothèque pour définir une image du produit',
      'he': 'אפשר גישה לספרייה כדי להגדיר תמונה של המוצר',
      'it':
          'Consenti l\'accesso alla libreria per impostare un\'immagine del prodotto',
      'zh_Hans': '允许访问库以设置产品图像',
    },
    'z9alt1gq': {
      'en': 'Recieve notifications?',
      'el': 'Λαμβάνετε ειδοποιήσεις;',
      'es': '¿Recibir notificaciones?',
      'fr': 'Recevoir des notifications ?',
      'he': 'לקבל התראות?',
      'it': 'Ricevi notifiche?',
      'zh_Hans': '收到通知？',
    },
    'yzo5je4f': {
      'en': 'We need access to the microphone to answer your response.',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'k3aqme34': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'f91horxz': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    's9uub90h': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0s9o0q1m': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'm0a6r5uv': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'fmnq0y4s': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '2ecstoml': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'u8dfm9f2': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'gjbx6hzk': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'n70kd594': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'o2pg6l1e': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'f34b1deh': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'o00qk1oc': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'tzosbe2d': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '4nwi9bxr': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '704qylhr': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '7hqdh2l3': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'ieftohf0': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0b783v0x': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'in3nhr8b': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '2tel2wol': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'npq67fgo': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'vot5ts87': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
