import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'el', 'fr', 'zh_Hans', 'es', 'it', 'he'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? elText = '',
    String? frText = '',
    String? zh_HansText = '',
    String? esText = '',
    String? itText = '',
    String? heText = '',
  }) =>
      [
        enText,
        elText,
        frText,
        zh_HansText,
        esText,
        itText,
        heText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // recipePage
  {
    'udh60zyp': {
      'en': 'Wheat Pancakes',
      'el': 'Τηγανίτες σιταριού',
      'es': 'Tortitas De Trigo',
      'fr': 'Crêpes De Blé',
      'he': 'פנקייק חיטה',
      'it': 'Pancake Di Grano',
      'zh_Hans': '小麦煎饼',
    },
    'dz3mqkqn': {
      'en': 'ProductTime',
      'el': 'ProductTime',
      'es': 'Hora del producto',
      'fr': 'Heure du produit',
      'he': 'ProductTime',
      'it': 'ProdottoTime',
      'zh_Hans': '产品时间',
    },
    'z3peqoot': {
      'en': 'ProductPrice',
      'el': 'Τιμή Προϊόντος',
      'es': 'Precio del producto',
      'fr': 'Prix ​​du produit',
      'he': 'מחיר מוצר',
      'it': 'Prezzo del prodotto',
      'zh_Hans': '产品价格',
    },
    'xhbucuyd': {
      'en': 'Instructions:',
      'el': 'Οδηγίες:',
      'es': 'Instrucciones:',
      'fr': 'Instructions:',
      'he': 'הוראות:',
      'it': 'Istruzioni:',
      'zh_Hans': '指示：',
    },
    '4qt2s2zq': {
      'en':
          '1 cup of all-purpose flour\n2 tablespoons of sugar\n2 teaspoons of baking powder\n½ teaspoon of salt\n1 cup of milk\n2 tablespoons of unsalted butter, melted, or vegetable oil\n1 large egg\n1 tablespoon of vegetable oil for cooking\nAssorted toppings, such as butter, maple syrup, confectioners’ sugar, honey, jams, preserves, sweetened whipped cream, or chocolate syrup',
      'el':
          '1 φλιτζάνι αλεύρι για όλες τις χρήσεις\n2 κουταλιές της σούπας ζάχαρη\n2 κουταλάκια του γλυκού μπέικιν πάουντερ\n½ κουταλάκι του γλυκού αλάτι\n1 φλιτζάνι γάλα\n2 κουταλιές της σούπας ανάλατο βούτυρο, λιωμένο ή φυτικό λάδι\n1 μεγάλο αυγό\n1 κουταλιά της σούπας φυτικό λάδι για μαγείρεμα\nΔιάφορες επικαλύψεις, όπως βούτυρο, σιρόπι σφενδάμου, ζάχαρη ζαχαροπλαστικής, μέλι, μαρμελάδες, κονσέρβες, ζαχαρούχα σαντιγί ή σιρόπι σοκολάτας',
      'es':
          '1 taza de harina para todo uso\n2 cucharadas de azúcar\n2 cucharaditas de polvo para hornear\n½ cucharadita de sal\n1 taza de leche\n2 cucharadas de mantequilla sin sal, derretida o aceite vegetal\n1 huevo grande\n1 cucharada de aceite vegetal para cocinar\nAderezos variados, como mantequilla, jarabe de arce, azúcar glas, miel, mermeladas, conservas, crema batida endulzada o jarabe de chocolate.',
      'fr':
          '1 tasse de farine tout usage\n2 cuillères à soupe de sucre\n2 cuillères à café de levure chimique\n½ cuillère à café de sel\n1 tasse de lait\n2 cuillères à soupe de beurre non salé, fondu ou d\'huile végétale\n1 œuf large\n1 cuillère à soupe d\'huile végétale pour la cuisson\nGarnitures assorties, comme du beurre, du sirop d\'érable, du sucre glace, du miel, des confitures, des conserves, de la crème fouettée sucrée ou du sirop de chocolat',
      'he':
          '1 כוס קמח לכל מטרה\n2 כפות סוכר\n2 כפיות אבקת אפייה\n½ כפית מלח\n1 כוס חלב\n2 כפות חמאה לא מומלחת, מומסת או שמן צמחי\nביצה 1 גדולה\n1 כף שמן צמחי לבישול\nתוספות מגוונות, כגון חמאה, סירופ מייפל, סוכר קונדיטורים, דבש, ריבות, שימורים, קצפת ממותקת או סירופ שוקולד',
      'it':
          '1 tazza di farina per tutti gli usi\n2 cucchiai di zucchero\n2 cucchiaini di lievito\n½ cucchiaino di sale\n1 tazza di latte\n2 cucchiai di burro non salato, fuso o olio vegetale\n1 uovo grande\n1 cucchiaio di olio vegetale per cucinare\nCondimenti assortiti, come burro, sciroppo d\'acero, zucchero a velo, miele, marmellate, conserve, panna montata zuccherata o sciroppo di cioccolato',
      'zh_Hans':
          '1 杯通用面粉\n2汤匙糖\n2 茶匙发酵粉\n½ 茶匙盐\n1 杯牛奶\n2汤匙无盐黄油、融化的或植物油\n1个大鸡蛋\n1汤匙烹饪用植物油\n各种配料，例如黄油、枫糖浆、糖果糖、蜂蜜、果酱、蜜饯、加糖生奶油或巧克力糖浆',
    },
    '79c9bdav': {
      'en': 'Ingredients:',
      'el': 'Συστατικά:',
      'es': 'Ingredientes:',
      'fr': 'Ingrédients:',
      'he': 'רכיבים:',
      'it': 'Ingredienti:',
      'zh_Hans': '原料：',
    },
    's35rkh93': {
      'en':
          'In a large bowl, whisk together the flour, sugar, baking powder, and salt.\n\nIn a small bowl, whisk together the milk, butter or oil, and egg.\n\nMake a well in the center of the flour mixture and pour in the milk mixture. Stir gently until just combined. Do not overmix. The batter should be slightly lumpy.\n\nLet the batter rest for 10 minutes.\n\nHeat a large skillet or griddle over medium-high heat and lightly grease with oil.\n\nDrop about ¼ cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface, about 2 to 3 minutes. Flip and cook until golden on the other side, about 1 to 2 minutes more.\n\nTransfer the pancakes to a baking sheet and keep warm in a 200°F oven until ready to serve.\n\nRepeat with the remaining batter, adding more oil as needed.\n\nServe the pancakes with your favorite toppings and enjoy!',
      'el':
          'Σε ένα μεγάλο μπολ χτυπάμε το αλεύρι, τη ζάχαρη, το μπέικιν πάουντερ και το αλάτι.\n\nΣε ένα μικρό μπολ, χτυπήστε μαζί το γάλα, το βούτυρο ή το λάδι και το αυγό.\n\nΚάνουμε μια λακκούβα στο κέντρο του μείγματος του αλευριού και ρίχνουμε μέσα το μείγμα του γάλακτος. Ανακατεύουμε απαλά μέχρι να ενωθούν. Μην ανακατεύετε υπερβολικά. Το κουρκούτι πρέπει να είναι ελαφρώς σβολιασμένο.\n\nΑφήνουμε το κουρκούτι να ξεκουραστεί για 10 λεπτά.\n\nΖεσταίνουμε ένα μεγάλο τηγάνι ή τηγάνι σε μέτρια προς δυνατή φωτιά και αλείφουμε ελαφρά με λάδι.\n\nΡίξτε περίπου ¼ φλιτζάνι ζύμη στο τηγάνι για κάθε τηγανίτα. Μαγειρέψτε μέχρι να σχηματιστούν φυσαλίδες στην επιφάνεια, περίπου 2 με 3 λεπτά. Γυρίστε και μαγειρέψτε μέχρι να ροδίσει από την άλλη πλευρά, περίπου 1 με 2 λεπτά ακόμα.\n\nΜεταφέρετε τις τηγανίτες σε ένα ταψί και τις κρατάτε ζεστές σε φούρνο στους 200°F μέχρι να τις σερβίρετε.\n\nΕπαναλάβετε με το υπόλοιπο κουρκούτι, προσθέτοντας περισσότερο λάδι όσο χρειάζεται.\n\nΣερβίρετε τα pancakes με τα αγαπημένα σας toppings και απολαύστε!',
      'es':
          'En un tazón grande, mezcle la harina, el azúcar, el polvo para hornear y la sal.\n\nEn un tazón pequeño, mezcle la leche, la mantequilla o el aceite y el huevo.\n\nHaga un hueco en el centro de la mezcla de harina y vierta la mezcla de leche. Revuelva suavemente hasta que esté combinado. No haga sobre mezcla. La masa debe quedar ligeramente grumosa.\n\nDeja reposar la masa durante 10 minutos.\n\nCalienta una sartén grande o plancha a fuego medio-alto y engrasa ligeramente con aceite.\n\nColoque aproximadamente ¼ de taza de masa en la sartén para cada panqueque. Cocine hasta que se formen burbujas en la superficie, aproximadamente de 2 a 3 minutos. Voltee y cocine hasta que esté dorado por el otro lado, aproximadamente de 1 a 2 minutos más.\n\nTransfiera los panqueques a una bandeja para hornear y manténgalos calientes en un horno a 200 °F hasta que estén listos para servir.\n\nRepita con la masa restante y agregue más aceite según sea necesario.\n\n¡Sirve los panqueques con tus ingredientes favoritos y disfruta!',
      'fr':
          'Dans un grand bol, mélanger la farine, le sucre, la levure chimique et le sel.\n\nDans un petit bol, fouetter ensemble le lait, le beurre ou l\'huile et l\'œuf.\n\nFaites un puits au centre du mélange de farine et versez-y le mélange de lait. Remuer doucement jusqu\'à ce que tout soit bien combiné. Ne pas trop mélanger. La pâte doit être légèrement grumeleuse.\n\nLaissez reposer la pâte 10 minutes.\n\nChauffer une grande poêle ou une plaque chauffante à feu moyen-vif et graisser légèrement avec de l\'huile.\n\nDéposez environ ¼ tasse de pâte dans la poêle pour chaque crêpe. Cuire jusqu\'à ce que des bulles se forment à la surface, environ 2 à 3 minutes. Retourner et cuire jusqu\'à ce qu\'il soit doré de l\'autre côté, environ 1 à 2 minutes de plus.\n\nTransférer les crêpes sur une plaque à pâtisserie et réserver au chaud dans un four à 200°F jusqu\'au moment de servir.\n\nRépétez avec le reste de la pâte, en ajoutant plus d\'huile si nécessaire.\n\nServez les crêpes avec vos garnitures préférées et dégustez !',
      'he':
          'בקערה גדולה, טורפים יחד את הקמח, הסוכר, אבקת האפייה והמלח.\n\nבקערה קטנה, טורפים יחד את החלב, החמאה או השמן והביצה.\n\nיוצרים גומה במרכז תערובת הקמח ויוצקים פנימה את תערובת החלב. מערבבים בעדינות רק עד לאיחוד. אין לערבב יתר על המידה. הבלילה צריכה להיות מעט גושית.\n\nנותנים לבלילה לנוח 10 דקות.\n\nמחממים מחבת גדולה או פסים על אש בינונית-גבוהה ומשמנים קלות בשמן.\n\nזרוק כ-¼ כוס הבלילה על המחבת עבור כל פנקייק. מבשלים עד שנוצרות בועות על פני השטח, בערך 2 עד 3 דקות. הופכים ומבשלים עד להזהבה בצד השני, בערך 1 עד 2 דקות נוספות.\n\nמעבירים את הלביבות לתבנית עם נייר אפייה ושומרים חמים בתנור בחום של 200 מעלות עד להגשה.\n\nחוזרים על הפעולה עם הבלילה שנותרה, מוסיפים עוד שמן לפי הצורך.\n\nהגישו את הפנקייקים עם התוספות האהובות עליכם ותהנו!',
      'it':
          'In una ciotola capiente, sbatti insieme la farina, lo zucchero, il lievito e il sale.\n\nIn una piccola ciotola, sbatti insieme il latte, il burro o l\'olio e l\'uovo.\n\nFormate una fontana al centro del composto di farina e versate il composto di latte. Mescolare delicatamente fino a quando non sarà appena combinato. Non mescolare eccessivamente. La pastella dovrebbe risultare leggermente grumosa.\n\nLasciare riposare la pastella per 10 minuti.\n\nScaldare una padella grande o una piastra a fuoco medio-alto e ungerla leggermente con olio.\n\nMetti circa ¼ di tazza di pastella nella padella per ogni pancake. Cuocere finché non si formano delle bolle in superficie, circa 2 o 3 minuti. Capovolgi e cuoci fino a doratura sull\'altro lato, circa 1 o 2 minuti in più.\n\nTrasferisci i pancake su una teglia e mantienili al caldo in un forno a 200 ° F fino al momento di servire.\n\nRipetere l\'operazione con la pastella rimanente, aggiungendo altro olio se necessario.\n\nServite i pancake con i vostri condimenti preferiti e buon appetito!',
      'zh_Hans':
          '在一个大碗中，将面粉、糖、泡打粉和盐搅拌在一起。\n\n在一个小碗中，将牛奶、黄油或油和鸡蛋搅拌在一起。\n\n在面粉混合物的中心挖一个洞，倒入牛奶混合物。轻轻搅拌直至完全混合。不要过度混合。面糊应该有点块状。\n\n让面糊静置 10 分钟。\n\n用中高火加热大煎锅或煎锅，并涂上少许油。\n\n将约 ¼ 杯面糊放入煎锅中，制作每个煎饼。煮约2至3分钟，直至表面出现气泡。翻转并煮至另一面呈金黄色，再煮约 1 至 2 分钟。\n\n将薄煎饼转移到烤盘上，并在 200°F 的烤箱中保温直至准备好上桌。\n\n对剩余的面糊重复上述步骤，根据需要添加更多的油。\n\n将煎饼配上您最喜欢的配料即可享用！',
    },
    'a4ikx5qk': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // CreateRecipe
  {
    'aosvo8j3': {
      'en': 'Find New Recipies',
      'el': 'Βρείτε νέες συνταγές',
      'es': 'Encuentra nuevas recetas',
      'fr': 'Trouver de nouvelles recettes',
      'he': 'מצא מתכונים חדשים',
      'it': 'Trova nuove ricette',
      'zh_Hans': '寻找新食谱',
    },
    'qvtmpdlw': {
      'en':
          'Provide a list of ingredients and we\'ll tell you what you can wake with them!',
      'el':
          'Δώστε μια λίστα με συστατικά και θα σας πούμε τι μπορείτε να ξυπνήσετε με αυτά!',
      'es':
          '¡Proporciona una lista de ingredientes y te diremos qué puedes despertar con ellos!',
      'fr':
          'Fournissez une liste d\'ingrédients et nous vous dirons ce que vous pouvez réveiller avec eux !',
      'he': 'ספק רשימה של מרכיבים ואנו אגיד לך מה אתה יכול להעיר איתם!',
      'it':
          'Fornisci un elenco di ingredienti e ti diremo cosa puoi svegliare con loro!',
      'zh_Hans': '提供成分清单，我们会告诉您可以用它们唤醒什么！',
    },
    'w3w2p5az': {
      'en': 'Enter the ingredients you have on hand',
      'el': 'Εισαγάγετε τα υλικά που έχετε στη διάθεσή σας',
      'es': 'Introduce los ingredientes que tienes a mano',
      'fr': 'Entrez les ingrédients que vous avez sous la main',
      'he': 'הזן את החומרים שיש לך בהישג יד',
      'it': 'Inserisci gli ingredienti che hai a portata di mano',
      'zh_Hans': '输入您现有的成分',
    },
    '2md05yfn': {
      'en': 'Ingredients...',
      'el': 'Συστατικά...',
      'es': 'Ingredientes...',
      'fr': 'Ingrédients...',
      'he': 'רכיבים...',
      'it': 'Ingredienti...',
      'zh_Hans': '原料...',
    },
    'r2x6x79t': {
      'en': 'Enter the condiments, seasoning, and sauces you have on hand.',
      'el':
          'Εισαγάγετε τα καρυκεύματα, τα καρυκεύματα και τις σάλτσες που έχετε στη διάθεσή σας.',
      'es': 'Ingresa los condimentos, aderezos y salsas que tengas a mano.',
      'fr':
          'Entrez les condiments, assaisonnements et sauces que vous avez sous la main.',
      'he': 'הכניסו את התבלינים, התיבול והרטבים שיש לכם בהישג יד.',
      'it':
          'Inserisci i condimenti, i condimenti e le salse che hai a portata di mano.',
      'zh_Hans': '输入您手头的调味品、调料和酱汁。',
    },
    'cdfr8sl5': {
      'en': 'Condiments, seasoning and sauces...',
      'el': 'Καρυκεύματα, καρυκεύματα και σάλτσες...',
      'es': 'Condimentos, aliños y salsas...',
      'fr': 'Condiments, assaisonnements et sauces...',
      'he': 'תבלינים, תיבול ורטבים...',
      'it': 'Condimenti, condimenti e salse...',
      'zh_Hans': '调味品、调料和酱料...',
    },
    'j9g4tgv0': {
      'en': 'Available leftovers (Optional)',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)',
      'es': 'Sobras disponibles (Opcional)',
      'fr': 'Restes disponibles (facultatif)',
      'he': 'שאריות זמינות (אופציונלי)',
      'it': 'Avanzi disponibili (facoltativo)',
      'zh_Hans': '可用的剩菜（可选）',
    },
    'w302ckd9': {
      'en': 'Available leftovers (Optional)...',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)...',
      'es': 'Sobras disponibles (Opcional)...',
      'fr': 'Restes disponibles (Facultatif)...',
      'he': 'שאריות זמינות (אופציונלי)...',
      'it': 'Avanzi disponibili (facoltativo)...',
      'zh_Hans': '可用的剩菜（可选）...',
    },
    '9box9vhz': {
      'en': 'Type of Meal',
      'el': 'Είδος Γεύματος',
      'es': 'Tipo de comida',
      'fr': 'Type de repas',
      'he': 'סוג הארוחה',
      'it': 'Tipo di pasto',
      'zh_Hans': '膳食类型',
    },
    'uc5kkya7': {
      'en': 'Please select what time of day you want the meal',
      'el': 'Επιλέξτε ποια ώρα της ημέρας θέλετε το γεύμα',
      'es': 'Por favor seleccione a qué hora del día desea la comida.',
      'fr':
          'Veuillez sélectionner l\'heure de la journée à laquelle vous souhaitez le repas',
      'he': 'אנא בחר באיזו שעה ביום אתה רוצה את הארוחה',
      'it': 'Seleziona l\'ora del giorno in cui desideri il pasto',
      'zh_Hans': '请选择您想要用餐的时间',
    },
    '2sekcuzu': {
      'en': 'Breakfast',
      'el': 'ΠΡΩΙΝΟ ΓΕΥΜΑ',
      'es': 'Desayuno',
      'fr': 'Petit-déjeuner',
      'he': 'ארוחת בוקר',
      'it': 'Colazione',
      'zh_Hans': '早餐',
    },
    'r2nlgwxf': {
      'en': 'Brunch',
      'el': 'Μεσημεριανό',
      'es': 'Desalmuerzo',
      'fr': 'Brunch',
      'he': 'בראנץ\'',
      'it': 'Brunch',
      'zh_Hans': '早午餐',
    },
    'amhlyrkb': {
      'en': 'Lunch',
      'el': 'Μεσημεριανό',
      'es': 'Almuerzo',
      'fr': 'Déjeuner',
      'he': 'ארוחת צהריים',
      'it': 'Pranzo',
      'zh_Hans': '午餐',
    },
    'do92tfg0': {
      'en': 'Dinner',
      'el': 'Βραδινό',
      'es': 'Cena',
      'fr': 'Dîner',
      'he': 'אֲרוּחַת עֶרֶב',
      'it': 'Cena',
      'zh_Hans': '晚餐',
    },
    'kb5cep1z': {
      'en': 'Available Time',
      'el': 'Διαθέσιμος χρόνος',
      'es': 'Tiempo disponible',
      'fr': 'Temps disponible',
      'he': 'זמן פנוי',
      'it': 'Tempo disponibile',
      'zh_Hans': '有空时间',
    },
    'hi7iwckb': {
      'en': 'Please select how much  time you have to make this meal',
      'el': 'Επιλέξτε πόσο χρόνο έχετε για να φτιάξετε αυτό το γεύμα',
      'es':
          'Por favor selecciona cuánto tiempo tienes para preparar esta comida.',
      'fr':
          'Veuillez sélectionner le temps dont vous disposez pour préparer ce repas',
      'he': 'אנא בחר כמה זמן יש לך להכין את הארוחה הזו',
      'it': 'Seleziona quanto tempo hai per preparare questo pasto',
      'zh_Hans': '请选择您需要多长时间来做这顿饭',
    },
    'eu1h115a': {
      'en': '5 min',
      'el': '5 λεπτά',
      'es': '5 minutos',
      'fr': '5 minutes',
      'he': '5 דקות',
      'it': '5 minuti',
      'zh_Hans': '5分钟',
    },
    '70p0wl0p': {
      'en': '15 min',
      'el': '15 λεπτά',
      'es': '15 minutos',
      'fr': '15 min',
      'he': '15 דקות',
      'it': '15 minuti',
      'zh_Hans': '15分钟',
    },
    '94sl5qjg': {
      'en': '30 min',
      'el': '30 λεπτά',
      'es': '30 minutos',
      'fr': '30 minutes',
      'he': '30 דק',
      'it': '30 minuti',
      'zh_Hans': '30分钟',
    },
    'mytzw9ng': {
      'en': '1 hour',
      'el': '1 ώρα',
      'es': '1 hora',
      'fr': '1 heure',
      'he': '1 שעה',
      'it': '1 ora',
      'zh_Hans': '1小时',
    },
    'p7hq20gh': {
      'en': '2 hours',
      'el': '2 ώρες',
      'es': '2 horas',
      'fr': '2 heures',
      'he': '2 שעות',
      'it': '2 ore',
      'zh_Hans': '2小时',
    },
    'jpyobpnv': {
      'en': 'infinite',
      'el': 'άπειρος',
      'es': 'infinito',
      'fr': 'infini',
      'he': 'אֵינְסוֹף',
      'it': 'infinito',
      'zh_Hans': '无穷',
    },
    '4dk7vxu3': {
      'en': 'Generate Recipies',
      'el': 'Δημιουργία συνταγών',
      'es': 'Generar recetas',
      'fr': 'Générer des recettes',
      'he': 'צור מתכונים',
      'it': 'Genera ricette',
      'zh_Hans': '生成食谱',
    },
    '1t9l4nbb': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '1tb1rivq': {
      'en': 'Menu',
      'el': 'Μενού',
      'es': 'Menú',
      'fr': 'Menu',
      'he': 'תַפרִיט',
      'it': 'Menù',
      'zh_Hans': '菜单',
    },
    'a0t2k0co': {
      'en': 'Light Mode',
      'el': 'Λειτουργία φωτός',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'he': 'מצב אור',
      'it': 'Modalità luce',
      'zh_Hans': '灯光模式',
    },
    '0oc6lxcz': {
      'en': 'Dark Mode',
      'el': 'Σκοτεινή λειτουργία',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'he': 'מצב כהה',
      'it': 'Modalità scura',
      'zh_Hans': '深色模式',
    },
    'nz47o0cg': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // Login
  {
    'pi2fp0xe': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'kqlvn0vt': {
      'en': 'Create Account',
      'el': 'Δημιουργήστε λογαριασμό',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'he': 'צור חשבון',
      'it': 'Creare un account',
      'zh_Hans': '创建账户',
    },
    'kl41bult': {
      'en': 'Create Account',
      'el': 'Δημιουργήστε λογαριασμό',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'he': 'צור חשבון',
      'it': 'Creare un account',
      'zh_Hans': '创建账户',
    },
    'z3ekx0l8': {
      'en': 'Let\'s get started by filling out the form below.',
      'el': 'Ας ξεκινήσουμε συμπληρώνοντας την παρακάτω φόρμα.',
      'es': 'Comencemos completando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'he': 'בואו נתחיל על ידי מילוי הטופס למטה.',
      'it': 'Iniziamo compilando il modulo sottostante.',
      'zh_Hans': '让我们开始填写下面的表格。',
    },
    'uww47kva': {
      'en': 'Email',
      'el': 'ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'he': 'אימייל',
      'it': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    '9p9aegbs': {
      'en': 'Password',
      'el': 'Κωδικός πρόσβασης',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'he': 'סיסמה',
      'it': 'Parola d\'ordine',
      'zh_Hans': '密码',
    },
    'xt2q79rm': {
      'en': 'Confirm Password',
      'el': 'Επιβεβαίωση Κωδικού',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'he': 'אשר סיסמה',
      'it': 'Conferma password',
      'zh_Hans': '确认密码',
    },
    '0zfk0v8x': {
      'en': 'Get Started',
      'el': 'Ξεκίνα',
      'es': 'Empezar',
      'fr': 'Commencer',
      'he': 'להתחיל',
      'it': 'Iniziare',
      'zh_Hans': '开始使用',
    },
    'f9x272es': {
      'en': 'Or sign up with',
      'el': 'Ή εγγραφείτε με',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'he': 'או להירשם עם',
      'it': 'Oppure registrati con',
      'zh_Hans': '或者注册',
    },
    'x7lvsg7m': {
      'en': 'Continue with Google',
      'el': 'Συνεχίστε με την Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'he': 'המשך עם גוגל',
      'it': 'Continua con Google',
      'zh_Hans': '继续使用谷歌',
    },
    'ywy6r8ja': {
      'en': 'Continue with Apple',
      'el': 'Συνεχίστε με την Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'he': 'המשך עם אפל',
      'it': 'Continua con Apple',
      'zh_Hans': '继续使用苹果',
    },
    '8ttpf53r': {
      'en': 'Log In',
      'el': 'Σύνδεση',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'he': 'התחברות',
      'it': 'Login',
      'zh_Hans': '登录',
    },
    'p3jq1rth': {
      'en': 'Welcome Back',
      'el': 'Καλως ορισες πισω',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'he': 'ברוך שובך',
      'it': 'Bentornato',
      'zh_Hans': '欢迎回来',
    },
    '1bzpl5f5': {
      'en': 'Fill out the information below in order to access your account.',
      'el':
          'Συμπληρώστε τις παρακάτω πληροφορίες για να αποκτήσετε πρόσβαση στον λογαριασμό σας.',
      'es': 'Complete la información a continuación para acceder a su cuenta.',
      'fr':
          'Remplissez les informations ci-dessous afin d\'accéder à votre compte.',
      'he': 'מלא את המידע למטה כדי לגשת לחשבון שלך.',
      'it': 'Compila le informazioni seguenti per accedere al tuo account.',
      'zh_Hans': '填写以下信息以访问您的帐户。',
    },
    '65ndiovm': {
      'en': 'Email',
      'el': 'ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'he': 'אימייל',
      'it': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'x4uu6huf': {
      'en': 'Password',
      'el': 'Κωδικός πρόσβασης',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'he': 'סיסמה',
      'it': 'Parola d\'ordine',
      'zh_Hans': '密码',
    },
    '6qvilc6k': {
      'en': 'Sign In',
      'el': 'Συνδεθείτε',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'he': 'להתחבר',
      'it': 'Registrazione',
      'zh_Hans': '登入',
    },
    'z5wonppu': {
      'en': 'Or sign in with',
      'el': 'Ή συνδεθείτε με',
      'es': 'O inicia sesión con',
      'fr': 'Ou connectez-vous avec',
      'he': 'או היכנס עם',
      'it': 'Oppure accedi con',
      'zh_Hans': '或者登录',
    },
    'o8kjh2lz': {
      'en': 'Continue with Google',
      'el': 'Συνεχίστε με την Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'he': 'המשך עם גוגל',
      'it': 'Continua con Google',
      'zh_Hans': '继续使用谷歌',
    },
    'bzh273nl': {
      'en': 'Continue with Apple',
      'el': 'Συνεχίστε με την Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'he': 'המשך עם אפל',
      'it': 'Continua con Apple',
      'zh_Hans': '继续使用苹果',
    },
    'kzsaoaen': {
      'en': 'Forgot Password?',
      'el': 'Ξεχάσατε τον κωδικό;',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'he': 'שכחת את הסיסמא?',
      'it': 'Ha dimenticato la password?',
      'zh_Hans': '忘记密码？',
    },
    'i6sso3fq': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // Inventory
  {
    'wqqyw4gl': {
      'en': 'Inventory',
      'el': 'Καταγραφή εμπορευμάτων',
      'es': 'Inventario',
      'fr': 'Inventaire',
      'he': 'מְלַאי',
      'it': 'Inventario',
      'zh_Hans': '存货',
    },
    '8ymlzker': {
      'en': 'List of current groceries',
      'el': 'Λίστα με τρέχοντα είδη παντοπωλείου',
      'es': 'Lista de comestibles actuales',
      'fr': 'Liste des courses actuelles',
      'he': 'רשימת מצרכים עדכניים',
      'it': 'Elenco della spesa corrente',
      'zh_Hans': '当前杂货清单',
    },
    '5c700uvt': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'a42e5p7u': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '1ngqwoj3': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'jtkd2si4': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'xn8o5053': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'rrsniy4r': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    '8cmltkz8': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'r3u97cna': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'dqk4daaq': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'oe9o9v4s': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'ffbdhbr4': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'mlk84ymp': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'wxto50y0': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    '47xsfdzy': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'kwedplak': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'c8z3iimk': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'pyrlkewb': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '4n17pyu3': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'ofh0rf85': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // HomePage
  {
    '3byzw7t1': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    't0j5ilae': {
      'en': 'Recipes',
      'el': 'Συνταγές',
      'es': 'Recetas',
      'fr': 'Recettes',
      'he': 'מתכונים',
      'it': 'Ricette',
      'zh_Hans': '食谱',
    },
    'smjtjrud': {
      'en': 'Inventory',
      'el': 'Καταγραφή εμπορευμάτων',
      'es': 'Inventario',
      'fr': 'Inventaire',
      'he': 'מְלַאי',
      'it': 'Inventario',
      'zh_Hans': '存货',
    },
    '29jgia0v': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    '1fp9839p': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '2xm16o17': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'm71yuliy': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'm8mzxvvl': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'ovfolrx6': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'jel2es31': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'fuskduy5': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    's426ux8e': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'm65ssgm5': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    '06ubw82x': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'e5u9khnp': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    '0113xoyc': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    '5zybi7rq': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    'ubvde3nz': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'pkm284jc': {
      'en': 'Title',
      'el': 'Τίτλος',
      'es': 'Título',
      'fr': 'Titre',
      'he': 'כותרת',
      'it': 'Titolo',
      'zh_Hans': '标题',
    },
    'sllg5clj': {
      'en': 'Subtext',
      'el': 'Υποκείμενο',
      'es': 'Trasfondo',
      'fr': 'Sous-texte',
      'he': 'סאבטקסט',
      'it': 'Sottotesto',
      'zh_Hans': '潜台词',
    },
    '7y2un2xy': {
      'en': '\$11.00',
      'el': '11,00 \$',
      'es': '\$11.00',
      'fr': '11,00 \$',
      'he': '\$11.00',
      'it': '\$ 11,00',
      'zh_Hans': '11.00 美元',
    },
    'z7q318wm': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '96tbeqpo': {
      'en': 'Profile',
      'el': 'Προφίλ',
      'es': 'Perfil',
      'fr': 'Profil',
      'he': 'פּרוֹפִיל',
      'it': 'Profilo',
      'zh_Hans': '轮廓',
    },
    'ykwudah9': {
      'en': 'Ask Copilot',
      'el': 'Ρωτήστε τον Copilot',
      'es': 'Preguntar al copiloto',
      'fr': 'Demandez au copilote',
      'he': 'תשאל קוטילוט',
      'it': 'Chiedi al copilota',
      'zh_Hans': '询问副驾驶',
    },
    'lnhxxh3t': {
      'en': 'Settings',
      'el': 'Ρυθμίσεις',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'he': 'הגדרות',
      'it': 'Impostazioni',
      'zh_Hans': '设置',
    },
    'iqmixj4b': {
      'en': 'Log Out',
      'el': 'Αποσύνδεση',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'he': 'להתנתק',
      'it': 'Disconnettersi',
      'zh_Hans': '登出',
    },
    's0row5j0': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // CreateRecipeCopy
  {
    'gy9sq5xl': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    'wcx9x69a': {
      'en': 'Find New Recipies',
      'el': 'Βρείτε νέες συνταγές',
      'es': 'Encuentra nuevas recetas',
      'fr': 'Trouver de nouvelles recettes',
      'he': 'מצא מתכונים חדשים',
      'it': 'Trova nuove ricette',
      'zh_Hans': '寻找新食谱',
    },
    'yc09jw4b': {
      'en':
          'Provide a list of ingredients and we\'ll tell you what you can wake with them!',
      'el':
          'Δώστε μια λίστα με συστατικά και θα σας πούμε τι μπορείτε να ξυπνήσετε με αυτά!',
      'es':
          '¡Proporciona una lista de ingredientes y te diremos qué puedes despertar con ellos!',
      'fr':
          'Fournissez une liste d\'ingrédients et nous vous dirons ce que vous pouvez réveiller avec eux !',
      'he': 'ספק רשימה של מרכיבים ואנו אגיד לך מה אתה יכול להעיר איתם!',
      'it':
          'Fornisci un elenco di ingredienti e ti diremo cosa puoi svegliare con loro!',
      'zh_Hans': '提供成分清单，我们会告诉您可以用它们唤醒什么！',
    },
    'kn6gnxfe': {
      'en': 'Enter the ingredients you have on hand',
      'el': 'Εισαγάγετε τα υλικά που έχετε στη διάθεσή σας',
      'es': 'Introduce los ingredientes que tienes a mano',
      'fr': 'Entrez les ingrédients que vous avez sous la main',
      'he': 'הזן את החומרים שיש לך בהישג יד',
      'it': 'Inserisci gli ingredienti che hai a portata di mano',
      'zh_Hans': '输入您现有的成分',
    },
    'xkhh2aqi': {
      'en': 'Ingredients...',
      'el': 'Συστατικά...',
      'es': 'Ingredientes...',
      'fr': 'Ingrédients...',
      'he': 'רכיבים...',
      'it': 'Ingredienti...',
      'zh_Hans': '原料...',
    },
    '3lg39rcu': {
      'en': 'Enter the condiments, seasoning, and sauces you have on hand.',
      'el':
          'Εισαγάγετε τα καρυκεύματα, τα καρυκεύματα και τις σάλτσες που έχετε στη διάθεσή σας.',
      'es': 'Ingresa los condimentos, aderezos y salsas que tengas a mano.',
      'fr':
          'Entrez les condiments, assaisonnements et sauces que vous avez sous la main.',
      'he': 'הכניסו את התבלינים, התיבול והרטבים שיש לכם בהישג יד.',
      'it':
          'Inserisci i condimenti, i condimenti e le salse che hai a portata di mano.',
      'zh_Hans': '输入您手头的调味品、调料和酱汁。',
    },
    'sr0aaoz1': {
      'en': 'Condiments, seasoning and sauces...',
      'el': 'Καρυκεύματα, καρυκεύματα και σάλτσες...',
      'es': 'Condimentos, aliños y salsas...',
      'fr': 'Condiments, assaisonnements et sauces...',
      'he': 'תבלינים, תיבול ורטבים...',
      'it': 'Condimenti, condimenti e salse...',
      'zh_Hans': '调味品、调料和酱料...',
    },
    '1zfr9wl7': {
      'en': 'Available leftovers (Optional)',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)',
      'es': 'Sobras disponibles (Opcional)',
      'fr': 'Restes disponibles (facultatif)',
      'he': 'שאריות זמינות (אופציונלי)',
      'it': 'Avanzi disponibili (facoltativo)',
      'zh_Hans': '可用的剩菜（可选）',
    },
    'twyn6tq8': {
      'en': 'Available leftovers (Optional)...',
      'el': 'Διαθέσιμα υπολείμματα (Προαιρετικά)...',
      'es': 'Sobras disponibles (Opcional)...',
      'fr': 'Restes disponibles (Facultatif)...',
      'he': 'שאריות זמינות (אופציונלי)...',
      'it': 'Avanzi disponibili (facoltativo)...',
      'zh_Hans': '可用的剩菜（可选）...',
    },
    'rfcztjx1': {
      'en': 'Type of Meal',
      'el': 'Είδος Γεύματος',
      'es': 'Tipo de comida',
      'fr': 'Type de repas',
      'he': 'סוג הארוחה',
      'it': 'Tipo di pasto',
      'zh_Hans': '膳食类型',
    },
    'h356zg9k': {
      'en': 'Please select what time of day you want the meal',
      'el': 'Επιλέξτε ποια ώρα της ημέρας θέλετε το γεύμα',
      'es': 'Por favor seleccione a qué hora del día desea la comida.',
      'fr':
          'Veuillez sélectionner l\'heure de la journée à laquelle vous souhaitez le repas',
      'he': 'אנא בחר באיזו שעה ביום אתה רוצה את הארוחה',
      'it': 'Seleziona l\'ora del giorno in cui desideri il pasto',
      'zh_Hans': '请选择您想要用餐的时间',
    },
    'tey5bxpw': {
      'en': 'Breakfast',
      'el': 'ΠΡΩΙΝΟ ΓΕΥΜΑ',
      'es': 'Desayuno',
      'fr': 'Petit-déjeuner',
      'he': 'ארוחת בוקר',
      'it': 'Colazione',
      'zh_Hans': '早餐',
    },
    'n3qjwlhz': {
      'en': 'Brunch',
      'el': 'Μεσημεριανό',
      'es': 'Desalmuerzo',
      'fr': 'Brunch',
      'he': 'בראנץ\'',
      'it': 'Brunch',
      'zh_Hans': '早午餐',
    },
    'ts13adfg': {
      'en': 'Lunch',
      'el': 'Μεσημεριανό',
      'es': 'Almuerzo',
      'fr': 'Déjeuner',
      'he': 'ארוחת צהריים',
      'it': 'Pranzo',
      'zh_Hans': '午餐',
    },
    'ibzhtnlo': {
      'en': 'Dinner',
      'el': 'Βραδινό',
      'es': 'Cena',
      'fr': 'Dîner',
      'he': 'אֲרוּחַת עֶרֶב',
      'it': 'Cena',
      'zh_Hans': '晚餐',
    },
    '3ydte78f': {
      'en': 'Available Time',
      'el': 'Διαθέσιμος χρόνος',
      'es': 'Tiempo disponible',
      'fr': 'Temps disponible',
      'he': 'זמן פנוי',
      'it': 'Tempo disponibile',
      'zh_Hans': '有空时间',
    },
    's837bdz9': {
      'en': 'Please select how much  time you have to make this meal',
      'el': 'Επιλέξτε πόσο χρόνο έχετε για να φτιάξετε αυτό το γεύμα',
      'es':
          'Por favor selecciona cuánto tiempo tienes para preparar esta comida.',
      'fr':
          'Veuillez sélectionner le temps dont vous disposez pour préparer ce repas',
      'he': 'אנא בחר כמה זמן יש לך להכין את הארוחה הזו',
      'it': 'Seleziona quanto tempo hai per preparare questo pasto',
      'zh_Hans': '请选择您需要多长时间来做这顿饭',
    },
    'i6drt0c4': {
      'en': '5 min',
      'el': '5 λεπτά',
      'es': '5 minutos',
      'fr': '5 minutes',
      'he': '5 דקות',
      'it': '5 minuti',
      'zh_Hans': '5分钟',
    },
    'yzkelw28': {
      'en': '15 min',
      'el': '15 λεπτά',
      'es': '15 minutos',
      'fr': '15 min',
      'he': '15 דקות',
      'it': '15 minuti',
      'zh_Hans': '15分钟',
    },
    'medi4uu4': {
      'en': '30 min',
      'el': '30 λεπτά',
      'es': '30 minutos',
      'fr': '30 minutes',
      'he': '30 דק',
      'it': '30 minuti',
      'zh_Hans': '30分钟',
    },
    'uqx41994': {
      'en': '1 hour',
      'el': '1 ώρα',
      'es': '1 hora',
      'fr': '1 heure',
      'he': '1 שעה',
      'it': '1 ora',
      'zh_Hans': '1小时',
    },
    '3q698n8m': {
      'en': '2 hours',
      'el': '2 ώρες',
      'es': '2 horas',
      'fr': '2 heures',
      'he': '2 שעות',
      'it': '2 ore',
      'zh_Hans': '2小时',
    },
    '33gi4lb6': {
      'en': 'infinite',
      'el': 'άπειρος',
      'es': 'infinito',
      'fr': 'infini',
      'he': 'אֵינְסוֹף',
      'it': 'infinito',
      'zh_Hans': '无穷',
    },
    'dj7b166f': {
      'en': 'Generate Recipies',
      'el': 'Δημιουργία συνταγών',
      'es': 'Generar recetas',
      'fr': 'Générer des recettes',
      'he': 'צור מתכונים',
      'it': 'Genera ricette',
      'zh_Hans': '生成食谱',
    },
    'tmqjionz': {
      'en': 'Menu',
      'el': 'Μενού',
      'es': 'Menú',
      'fr': 'Menu',
      'he': 'תַפרִיט',
      'it': 'Menù',
      'zh_Hans': '菜单',
    },
    'bqr8htar': {
      'en': 'Light Mode',
      'el': 'Λειτουργία φωτός',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'he': 'מצב אור',
      'it': 'Modalità luce',
      'zh_Hans': '灯光模式',
    },
    'ejdn2az6': {
      'en': 'Dark Mode',
      'el': 'Σκοτεινή λειτουργία',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'he': 'מצב כהה',
      'it': 'Modalità scura',
      'zh_Hans': '深色模式',
    },
    'skszh1cn': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // SearchImage
  {
    '0viu9dkb': {
      'en': 'Upload an Image',
      'el': 'Ανεβάστε μια εικόνα',
      'es': 'Subir una imagen',
      'fr': 'Télécharger une image',
      'he': 'העלה תמונה',
      'it': 'Carica un\'immagine',
      'zh_Hans': '上传图片',
    },
    '5baaij54': {
      'en': 'OR',
      'el': 'Ή',
      'es': 'O',
      'fr': 'OU',
      'he': 'אוֹ',
      'it': 'O',
      'zh_Hans': '或者',
    },
    'cqwxyx1x': {
      'en': 'Input URL',
      'el': 'Εισαγωγή URL',
      'es': 'URL de entrada',
      'fr': 'URL d\'entrée',
      'he': 'הזן כתובת אתר',
      'it': 'Inserisci l\'URL',
      'zh_Hans': '输入网址',
    },
    'ojg7s49j': {
      'en': 'Context',
      'el': 'Συμφραζόμενα',
      'es': 'Contexto',
      'fr': 'Contexte',
      'he': 'הֶקשֵׁר',
      'it': 'Contesto',
      'zh_Hans': '语境',
    },
    'z0jvh04n': {
      'en': 'Does it still look good or its spoilt?',
      'el': 'Εξακολουθεί να φαίνεται καλό ή είναι χαλασμένο;',
      'es': '¿Aún se ve bien o está estropeado?',
      'fr': 'Est-ce qu\'il a toujours l\'air bien ou est-il gâté ?',
      'he': 'האם זה עדיין נראה טוב או שהוא מפונק?',
      'it': 'Ha ancora un bell\'aspetto o è rovinato?',
      'zh_Hans': '它看起来还不错还是已经被破坏了？',
    },
    '2exuj78i': {
      'en': 'Copilot\'s Response',
      'el': 'Η απάντηση του Copilot',
      'es': 'La respuesta del copiloto',
      'fr': 'Réponse du copilote',
      'he': 'תגובת פיילוט',
      'it': 'La risposta del copilota',
      'zh_Hans': '副驾驶的回应',
    },
    '36mb8lzo': {
      'en': 'Ask about Product',
      'el': 'Ρωτήστε για το προϊόν',
      'es': 'Preguntar sobre el producto',
      'fr': 'Renseignez-vous sur le produit',
      'he': 'שאל על המוצר',
      'it': 'Chiedi informazioni sul prodotto',
      'zh_Hans': '询问产品',
    },
    '6qbrmssz': {
      'en': 'Ask about a product you have',
      'el': 'Ρωτήστε για ένα προϊόν που έχετε',
      'es': 'Pregunta por algún producto que tengas',
      'fr': 'Renseignez-vous sur un produit que vous possédez',
      'he': 'שאל על מוצר שיש לך',
      'it': 'Chiedi informazioni su un prodotto che possiedi',
      'zh_Hans': '询问您拥有的产品',
    },
    '63q4jft6': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // TalkToAI
  {
    'w49y0g2k': {
      'en': 'Chef Copilot',
      'el': 'Σεφ Copilot',
      'es': 'Chef copiloto',
      'fr': 'Chef copilote',
      'he': 'שף Copilot',
      'it': 'Cuoco Copilota',
      'zh_Hans': '副驾驶厨师',
    },
    '27xzotz5': {
      'en': 'Tap to Speak',
      'el': 'Πατήστε για να μιλήσετε',
      'es': 'Toca para hablar',
      'fr': 'Appuyez pour parler',
      'he': 'הקש כדי לדבר',
      'it': 'Tocca per parlare',
      'zh_Hans': '点击说话',
    },
    'xcsixe93': {
      'en': 'Home',
      'el': 'Σπίτι',
      'es': 'Hogar',
      'fr': 'Maison',
      'he': 'בית',
      'it': 'Casa',
      'zh_Hans': '家',
    },
  },
  // settings
  {
    'csd0hnif': {
      'en': 'Settings Page',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'o03ur49r': {
      'en': 'My Subscription',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '8kafvl9h': {
      'en': 'Getting Started',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'mtlehkdo': {
      'en': 'About Us',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '6vuvz4zb': {
      'en': 'Help',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'dp3spvav': {
      'en': 'Privacy Policy',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '6ohd1h60': {
      'en': 'Terms & Conditions',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'ue86jpkp': {
      'en': 'Follow us on',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'hrklg4eo': {
      'en': 'App Versions',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '4u035r7s': {
      'en': 'v0.0.1',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'ebt2j7cq': {
      'en': 'Log Out',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'zstomggv': {
      'en': 'Home',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
  },
  // option
  {
    'xdgeubbj': {
      'en': 'Add Product',
      'el': 'Προσθήκη προϊόντος',
      'es': 'Agregar producto',
      'fr': 'Ajouter un produit',
      'he': 'הוסף מוצר',
      'it': 'Aggiungi prodotto',
      'zh_Hans': '添加产品',
    },
    's06sy6ue': {
      'en': 'Item Name',
      'el': 'Ονομα προϊόντος',
      'es': 'Nombre del árticulo',
      'fr': 'Nom de l\'article',
      'he': 'שם הפריט',
      'it': 'Nome dell\'elemento',
      'zh_Hans': '项目名',
    },
    'bp5btcdx': {
      'en': 'Quantity',
      'el': 'Ποσότητα',
      'es': 'Cantidad',
      'fr': 'Quantité',
      'he': 'כַּמוּת',
      'it': 'Quantità',
      'zh_Hans': '数量',
    },
    'n7qtjf2l': {
      'en': 'Price',
      'el': 'Τιμή',
      'es': 'Precio',
      'fr': 'Prix',
      'he': 'מחיר',
      'it': 'Prezzo',
      'zh_Hans': '价格',
    },
    '8yu7i0ld': {
      'en': 'Save',
      'el': 'Αποθηκεύσετε',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'he': 'להציל',
      'it': 'Salva',
      'zh_Hans': '节省',
    },
  },
  // tray
  {
    '835sccoa': {
      'en': 'Ask Copilot',
      'el': 'Ρωτήστε τον Copilot',
      'es': 'Preguntar al copiloto',
      'fr': 'Demandez au copilote',
      'he': 'תשאל קוטילוט',
      'it': 'Chiedi al copilota',
      'zh_Hans': '询问副驾驶',
    },
    'n13pgude': {
      'en': 'Create Recipe',
      'el': 'Δημιουργία συνταγής',
      'es': 'Crear receta',
      'fr': 'Créer une recette',
      'he': 'צור מתכון',
      'it': 'Crea ricetta',
      'zh_Hans': '创建食谱',
    },
    'yugna71g': {
      'en': 'Add Product',
      'el': 'Προσθήκη προϊόντος',
      'es': 'Agregar producto',
      'fr': 'Ajouter un produit',
      'he': 'הוסף מוצר',
      'it': 'Aggiungi prodotto',
      'zh_Hans': '添加产品',
    },
  },
  // Miscellaneous
  {
    'og69irt4': {
      'en': 'Button',
      'el': 'Κουμπί',
      'es': 'Botón',
      'fr': 'Bouton',
      'he': 'לַחְצָן',
      'it': 'Pulsante',
      'zh_Hans': '按钮',
    },
    'mnhc0oi3': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'fnlxb6np': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '35w160b6': {
      'en': 'Allow access to library to set an image of product',
      'el':
          'Επιτρέψτε την πρόσβαση στη βιβλιοθήκη για να ορίσετε μια εικόνα του προϊόντος',
      'es':
          'Permitir el acceso a la biblioteca para configurar una imagen del producto',
      'fr':
          'Autoriser l\'accès à la bibliothèque pour définir une image du produit',
      'he': 'אפשר גישה לספרייה כדי להגדיר תמונה של המוצר',
      'it':
          'Consenti l\'accesso alla libreria per impostare un\'immagine del prodotto',
      'zh_Hans': '允许访问库以设置产品图像',
    },
    'z9alt1gq': {
      'en': 'Recieve notifications?',
      'el': 'Λαμβάνετε ειδοποιήσεις;',
      'es': '¿Recibir notificaciones?',
      'fr': 'Recevoir des notifications ?',
      'he': 'לקבל התראות?',
      'it': 'Ricevi notifiche?',
      'zh_Hans': '收到通知？',
    },
    'yzo5je4f': {
      'en': 'We need access to the microphone to answer your response.',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'k3aqme34': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'f91horxz': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    's9uub90h': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0s9o0q1m': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'm0a6r5uv': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'fmnq0y4s': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '2ecstoml': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'u8dfm9f2': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'gjbx6hzk': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'n70kd594': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'o2pg6l1e': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'f34b1deh': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'o00qk1oc': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'tzosbe2d': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '4nwi9bxr': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '704qylhr': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '7hqdh2l3': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'ieftohf0': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '0b783v0x': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'in3nhr8b': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    '2tel2wol': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'npq67fgo': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
    'vot5ts87': {
      'en': '',
      'el': '',
      'es': '',
      'fr': '',
      'he': '',
      'it': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
